# Generated by Django 3.2.25 on 2024-08-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='email_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
